### ISSUE TITLE
Frequency filtering

### ISSUE THREAD

**Issue by crimeacs** [asteroid-team/torch-audiomentations#98]
Frequency filtering produces artifacts at the beginning and the end of the signal. I suggest using tapering like this:

```
def taper(waveform, func, max_percentage, max_length=None):

        npts = len(waveform)

        # store all constraints for maximum taper length
        max_half_lenghts = []
        if max_percentage is not None:
            max_half_lenghts.append(int(max_percentage * npts))
        if max_length is not None:
            max_half_lenghts.append(int(max_length * self.stats.sampling_rate))

        # add full trace length to constraints
        max_half_lenghts.append(int(npts / 2))
        # select shortest acceptable window half-length
        wlen = min(max_half_lenghts)
        
        if 2 * wlen == npts:
            taper_sides = func(2 * wlen)
        else:
            taper_sides = func(2 * wlen + 1)
        taper = torch.tensor(np.hstack((taper_sides[:wlen], np.ones(npts - 2 * wlen),
                               taper_sides[len(taper_sides) - wlen:])))

        waveform *= taper
        return waveform

input = torch.randn(size=(100,))
a = taper(input, func=torch.hann_window, max_percentage=0.05)
```

**Comment by iver56** [comment]
Can you please help me poinpoint the issue a bit better? E.g. show a waveform, share some audio files or show a spectrogram? I just listened to some low-pass-filtered, high-pass-filtered and band-pass-filtered outputs, and zoomed in on the start and the end of the waveforms, and found nothing noteworthy. After I understand the issue, I can understand whether tapering is a good solution, or if the issue should be fixed in the core algorithm instead.

I've attached the audio examples that I investigated:

[filter_examples.zip](https://github.com/asteroid-team/torch-audiomentations/files/6953198/filter_examples.zip)

![bilde](https://user-images.githubusercontent.com/1470603/128683415-905bc8bc-e49a-486e-ac30-582547ac0587.png)

![spectrograms](https://user-images.githubusercontent.com/1470603/128683993-6106080d-c446-4304-a017-339a507cd6ec.gif)

**Comment by crimeacs** [comment]
Perhaps you are right. I cannot reproduce this behaviour anymore, so perhaps I had some other problem in the pipeline that was leading to this behaviour.

**Comment by iver56** [comment]
Ok, if you're able to narrow it down, please share your findings. In that case this issue can be reopened or a new one can be created
